# These are supported funding model platforms
THONG NGO
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username: thongngo1, thongngo2   
open_collective: # Replace with a single Open Collective username: thongngo1
ko_fi: # Replace with a single Ko-fi username: thongngo2
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username: thongngo1
issuehunt: # Replace with a single IssueHunt username: thongngo2
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
https://vbtc.exchange, https://bitcoinvn.io , https://pay.bitcoinvn.io , https://bitcoinnew.com
